uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/NotificationPopupView.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/NotificationPopupsManagerView.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/animations/LinearFadeInAnimation.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/animations/LinearFadeOutAnimation.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/animations/Pause.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/animations/SequencedAnimation.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/notifications/animations/Sequencer.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/WorkbenchCss.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/notification/NotificationManager.java
uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/client/resources/css/workbench.css

In this PR, the notification mechanism from [appformer](https://github.com/kiegroup/appformer/) is restored.
All necessary classes were copied as-is from appformer, 
though some minor changes had to be made in order to make the code compatible with this repository. 
Please keep in mind that this notification mechanism will probably be replaced in favor of each channel's approach.
For now, let's use this code so things are kept the way it was.
Example: Error notification is shown when loading an invalid dmn file in a scesim file
**Note**: This code only adds the infrastructure for showing the notification popup. No notification message has been changed.

KOGITO-5082: Restore the notification mechanism

---

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyBootstrapper.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyClientBundle.java

The errors on the Jira point to Monaco not being loaded properly at the moment we try to register the FEEL language. After several attempts of making Monaco be lazily loaded properly, I found out that the code is too much reliant on it being synchronous, so making it sync again is the easiest and most reliable solution for now. 
This adds the Monaco editors bundle (~2mb) to the GWT bundle again, though.

KOGITO-5068: Online DMN Editor won't load after several tabs are opened

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/FlowActionsToolboxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/MorphActionsToolboxView.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/AbstractActionsToolboxViewTest.java

Hi @romartin, @karreiro, 
I updated East and South toolboxes as discussed on the Jira issue:
To test it you can use
* VS [Code plugin](https://drive.google.com/file/d/1AIs_vQd-8ewPTd-Md_Cb1CKoiDJ11IQk/view?usp=sharing)
* or [Standalone editor](https://drive.google.com/file/d/1BDMMTpS4yaQvrXqzjQ5A29rVM-GTsIWs/view?usp=sharing)
Thank you!

KOGITO-4977: Stunner - Texts overlap toolboxes

---

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/ScenarioSimulationEditorEntryPoint.java

**JIRA**: [KOGITO-5135](https://issues.redhat.com/browse/KOGITO-5135): [SceSim Designer] HiDPI is not working as expected
**VS Code plugin**: [plugin](https://www.dropbox.com/s/tqm9um6loy3asem/KOGITO-5135.vsix?dl=0)
--
It's the same fix introduced by https://github.com/kiegroup/kogito-editors-java/pull/12, but applied in the SceSim editor.
--
Before:
After:

KOGITO-5135: [SceSim Designer] HiDPI is not working as expected

---

.github/workflows/bump_version.yml

This PR introduces a workflow analog to the "Bump version workflow" (https://github.com/kiegroup/kogito-editors-java/pull/39). However, in this case it creates the release branch automatically.

Workflow for creating the release branch

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/shape/def/CustomTaskShapeDef.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/shape/def/CustomTaskShapeDefTest.java

If an item could not be found in the workiItemDefinitionRegistry a null exception was thrown interrupting the load process.
**JIRA**: [KOGITO-5011](https://issues.redhat.com/browse/KOGITO-5011)
**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3636
**VS Code**: [VSCode Extension](https://drive.google.com/file/d/1j1NVlRrXkcO9rE8o0E402RWC-p62i_ZJ/view?usp=sharing)

KOGITO-5011 - Unknown Custom tasks in Designer makes Diagram Explorer empty

---

kogito-editors-js/package.json

https://issues.redhat.com/browse/BXMSPROD-1340
I didn't find a better way to avoid `--registry=X` flag error running yarn build:prod
```
[INFO] Running 'yarn build:prod --registry=RH_repo' in /home/jenkins/workspace/PROD_kogito-tooling.nightly_main/kiegroup_kogito-editors-java/kogito-editors-js
[INFO] yarn run v1.22.10
[INFO] $ rimraf dist && yarn format:check && lerna run build:prod --stream --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
[INFO] $ prettier --check .
[INFO] Checking formatting...
[INFO] All matched files use Prettier code style!
[INFO] ERR! lerna Unknown argument: registry
[INFO] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```
[webpack-cli] …
```

BXMSPROD-1340 kogito-tooling nightly

---

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientParser.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientParserTest.java
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/resources/org/kie/workbench/common/stunner/bpmn/client/workitem/importPartIgnored.wid
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/resources/org/kie/workbench/common/stunner/bpmn/client/workitem/multiLineComments.wid
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/resources/org/kie/workbench/common/stunner/bpmn/client/workitem/singleLineComments.wid

Hi @romartin, @domhanak,
now it is possible to use comments (both single and multi line) and imports in WID files.
see [VS Code extension](https://drive.google.com/file/d/10tCqW6yruYsebGY9V-6JR88EMD6IGOcS/view?usp=sharing) for tests. Thank you!

KOGITO-5549 - WID files with comments and Imports can't be loaded

---

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandler.java
drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/AbstractScesimGridModel.java
drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandlerTest.java
drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/AbstractScesimGridModelTest.java

**JIRA**: https://issues.redhat.com/browse/KOGITO-5571
@jomarko This PR fixes the 2^ issue you found here https://github.com/kiegroup/drools-wb/pull/1503#pullrequestreview-703931429 . Considering you found it, I assign the QE review to you, but please feel free to reassign.
Step to reproduce: 
- Create a new Test Scenario (RULE)
- Form "Data Object" tab, add any Java class available. (eg. Integer)
- Add the Integer > value property in the grid
- Try to re-assign the same column to an expression, selecting "Integer" class in the Test Tools.
- Nothing happens
- (the same occurs if you assign the expression first and then reassign it with Integer > value.
Same fix introduced in BC here: https://github.com/kiegroup/drools-wb/pull/1504

KOGITO-5571: No effects when assigning a not-expression Simple Type column to expression type (and viceversa)

---

kogito-editors-js/packages/boxed-expression-component/src/components/Resizer/Resizer.css

**Jira**: [KOGITO-5728](https://issues.redhat.com/browse/KOGITO-5728): [DMN Designer] New Boxed Expression editor - Remove "|" grip from the new boxed expression editor

KOGITO-5728: [DMN Designer] New Boxed Expression editor - Remove "|" grip from the new boxed expression editor

---

kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LineSpliceAcceptorControlImpl.java
kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LineSpliceAcceptorControlImplTest.java
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/pom.xml
kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/LineSpliceAcceptorControl.java
lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/wires/ILineSpliceAcceptor.java
lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresContainmentControlImpl.java
lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresLineSpliceControlImpl.java
lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresLineSpliceControlImplTest.java
lienzo-webapp/src/main/java/org/kie/lienzo/client/LineSpliceExample.java

Hey @romartin, please could you review this PR?
**JIRA**: [KOGITO-5676](https://issues.redhat.com/browse/KOGITO-5676)
**VS Code**: [plugin](https://drive.google.com/file/d/1yGvvu7NSdkIwhpgRHqrcYDOdXO4VF7uV/view?usp=sharing)
Thanks

KOGITO-5676: BPMN Editor - Containment not working when Node overlaps the Connector while splicing

---

.ci/jenkins/dsl/jobs.groovy

Folders in jenkins workspace are generated according to the job ID. Whitespaces in the ID causes an issues.

KOGITO-5642 Fix CI job ID

---

kogito-editors-js/packages/boxed-expression-component/src/__tests__/__mocks__/monacoMock.js
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/BoxedExpressionEditor/__snapshots__/BoxedExpressionEditor.test.tsx.snap
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/SelectionBox/CellSelectionBox.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/SelectionBox/SelectionBox.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/Table/EditableCell.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/Table/Table.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/Table/common/CopyAndPasteUtils.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/Table/common/TableUtils.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/BoxedExpressionEditor/BoxedExpressionEditor.css
kogito-editors-js/packages/boxed-expression-component/src/components/BoxedExpressionEditor/BoxedExpressionEditor.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/LiteralExpression/LiteralExpression.css
kogito-editors-js/packages/boxed-expression-component/src/components/RelationExpression/RelationExpression.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Resizer/Resizer.css
kogito-editors-js/packages/boxed-expression-component/src/components/SelectionBox/CellSelectionBox.css
kogito-editors-js/packages/boxed-expression-component/src/components/SelectionBox/CellSelectionBox.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/SelectionBox/SelectionBox.css
kogito-editors-js/packages/boxed-expression-component/src/components/SelectionBox/SelectionBox.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/SelectionBox/index.ts
kogito-editors-js/packages/boxed-expression-component/src/components/Table/EditableCell.css
kogito-editors-js/packages/boxed-expression-component/src/components/Table/EditableCell.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Table/Table.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Table/common/CopyAndPasteUtils.ts
kogito-editors-js/packages/boxed-expression-component/src/components/Table/common/TableUtils.ts
kogito-editors-js/packages/boxed-expression-component/src/components/Table/common/index.ts

**JIRAs:**
- [KOGITO-3656](https://issues.redhat.com/browse/KOGITO-3656): [DMN Designer] New boxed expression editor - Support copy/paste integration with other spreadsheets
- [KOGITO-5649](https://issues.redhat.com/browse/KOGITO-5649): [DMN Designer] New boxed expression editor - Support single/multiple cells highlight
Here's the live demo: [karreiro.com/kogito-editors-java](https://karreiro.com/kogito-editors-java/)
---

KOGITO-3656/KOGITO-5649: Support copy/paste integration with other spreadsheets / Support single/multiple cells highlight

---

kogito-editors-js/packages/boxed-expression-component/src/__tests__/components/Resizer/dom/Cell.test.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Resizer/Resizer.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Resizer/dom/Cell.ts

Jira: [KOGITO-5909](https://issues.redhat.com/browse/KOGITO-5909): [DMN Designer] New Boxed Expression editor - DMN Expression column width is updated too many times in some scenarios
**Before:**
**After:**

KOGITO-5909: [DMN Designer] New Boxed Expression editor - DMN Expression column width is updated too many times in some scenarios

---

appformer-bom/pom.xml
errai-bom/pom.xml
pom.xml

JIRA: https://issues.redhat.com/browse/KOGITO-5901
In this PR I managed all **depandabot** alerts. Please consider, all the involved dependencies are already managed in the parent pom `kie-parent`, so the common solution I adopted is to inherit the versions from that pom. In detail:
- **org.jsoup:jsoup**: Defined and managed in `kie-parent`. [A PR is already opened there to update the version](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1731). I think we can safely refer to `kie-parent`, so I removed it.
- **org.apache.httpcomponents:httpclient**: Defined and managed in `kie-parent`. Already updated to the last version `4.5.13` due to this ([RHPAM-3234](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1529)). Therefore, even if `GWT 2.9.0` refers to version …

KOGITO-5901: [DMN/BPMN/SceSim] Check dependabot alerts

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/template/dmn-documentation-template.html

- https://issues.redhat.com/browse/KOGITO-6033

KOGITO-6033: Make DMN data types documentation entries readable

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/drd/DRDNameChangerView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/drd/DRDNameChangerViewTest.java

JIRA: https://issues.redhat.com/browse/KOGITO-6021
Steps to reproduce: 
- Create a Decision Node;
- Click on DRD Action -> Create
- Try to update the `new-diagram` that appeared above (Press ENTER when the new value is assigned)
- Browser freezes
Fix: During every rename action, a process is fired to update the reference in multiple places of the editor.  This process is fired when the user press ENTER in the input element OR the input element loses focus (blur) (eg. pressing in another point of the page).
Unfortunately, pressing ENTER will start the process and at its end, a blur event is fired duplicating the process which leads eventually to freeze the browser.
To fix it, I start the rename update process ONLY if the new value is different than the original.

KOGITO-6021: [DMN Designer] Multiple DRDs - Renaming a DRD freezes the browser

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
kogito-editors-js/packages/boxed-expression-component/showcase/src/index.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/BoxedExpressionEditor/BoxedExpressionEditor.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/BoxedExpressionEditor/base-no-reset-wrapped.css

Fixing CSS rules compatibility issue with keyboard shortcuts section, due to inclusion `react-core` inside the `boxed-expression-component`, provided by PF.

KOGITO-6188: [DMN Designer] The keyboard shortcuts modal CSS from the DMN Editor is broken

---

lienzo-webapp/pom.xml

This a fix for the warning from build:
Some problems were encountered while building the effective model for org.kie.kogito:lienzo-webapp:war:8.5.2-SNAPSHOT
Warning:  'profiles.profile[GWT2].plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:gwt-maven-plugin @ line 239, column 14
Warning:
Warning:  It is highly recommended to fix these problems because they threaten the stability of your build.
Warning:
Warning:  For this reason, future Maven versions might no longer support building such malformed projects.
Warning:

Remove duplicit gwt-maven-plugin definition

---

.github/workflows/publish_release_artifacts_npm.yml

This PR fixes the publishing version of the [boxed-expression-component](https://www.npmjs.com/package/boxed-expression-component) and the [feel-input-component](https://www.npmjs.com/package/feel-input-component).
`npm version` changes only the kogito-editors-js `package.json`.
`lerna version` changes all kogito-editors-js packages to the specified version.

Update NPM packages version before publishing

---

kogito-editors-js/packages/boxed-expression-component/src/api/ContextEntry.ts
kogito-editors-js/packages/boxed-expression-component/src/components/ContextExpression/ContextEntryInfo.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/DecisionTableExpression/DecisionTableExpression.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Table/Table.tsx
kogito-editors-js/packages/boxed-expression-component/src/components/Table/TableHandler.tsx

https://issues.redhat.com/browse/KOGITO-6262
Fix both issues reported on KOGITO-6262
- New columns have the correct name
https://user-images.githubusercontent.com/24302289/143435767-504efd57-0405-4b8f-b84b-0abefc12af7d.mp4
- The DecisionTableExpression name is now syncronized with its parent.
https://user-images.githubusercontent.com/24302289/143435792-5c7726ee-81cb-4dab-87a1-d246cbbf39b8.mp4

KOGITO-6262: Regressions on DecisionTable, after KOGITO-5078

---

lienzo-core/src/main/java/com/ait/lienzo/client/widget/DragContext.java
lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelDragLimitEventDetail.java
lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelEvents.java
lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelHandlerManager.java
lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelPrimitiveDragEventDetail.java
lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/ScrollablePanel.java
lienzo-tests/src/test/java/com/ait/lienzo/client/widget/DragContextTest.java
lienzo-tests/src/test/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelDragLimitEventDetailTest.java
lienzo-tests/src/test/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelEventsTest.java
lienzo-tests/src/test/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelPrimitiveDragEventDetailTest.java

The canvas now expands/scrolls automatically anytime a primitive is dragged beyond control limits.
**JIRA**: [KOGITO-6045](https://issues.redhat.com/browse/KOGITO-6045)
**DMN Editor**: [Web App (.war)](https://drive.google.com/file/d/1VgcMBedpD5w6-S4j07e9U1XRO20DsI5w/view?usp=sharing)
**BPMN Editor**: [Web App (.war)](https://drive.google.com/file/d/1q4xiMKpMzjYOu1MTGJZ_sh4gyeVoZqmX/view?usp=sharing)
**VS Code**: [VSCode Extension](https://drive.google.com/file/d/1h4dLGBfL5Og5h8Gqf-SLH4Zn-WWeuGfe/view?usp=sharing)

KOGITO-6045 - Scroll automatically expandable canvas

---

kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumeration.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumerationView.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/item/DataTypeConstraintEnumerationItem.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/DataTypeConstraintEnumerationTest.java
kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/enumeration/item/DataTypeConstraintEnumerationItemTest.java

As part of this PR we:
- prevent user from defining same enumeration item multiple times: https://issues.redhat.com/browse/DROOLS-5197
- commit all enumeration items in edit mode by click on single checkbox: https://issues.redhat.com/browse/DROOLS-5744

DROOLS-5197,5744 - DMN Enumeration constraint editor small enhancements

---

errai-bom/pom.xml

`dependabot` reported a vulnerability with a netty dependency here https://github.com/kiegroup/kogito-editors-java/pull/189.
After a check, I noticed no netty dependency is actively used in the project, so we can safely removed it to solve the reported issue.

KOGITO-5901: Resolving dependabot alerts
