kiegroup/kogito-editors-java

- .github/workflows/ci.yml
- drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/pom.xml
- drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-testing/pom.xml
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/pom.xml
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/pom.xml
- Minor improvements to the CI workflow
- `Xmx` reduced from `gwt-maven-plugin` to avoid memory issues
> Improve CI

- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/DMNKogitoCommonEntryPoint.java
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/DMNKogitoCommonEntryPointTest.java
**JIRA**: [KOGITO-4530](https://issues.redhat.com/browse/KOGITO-4530): [DMN Designer] Boxed Expressions - Decision Tables - HiDPI is not working as expected
--
Cherry-picked from https://github.com/kiegroup/kie-wb-common/pull/3627
--
**VS Code plugin without this PR applied**: [8.0.0 plugin](https://www.dropbox.com/s/goihljb5n0f3q9v/current-8.0.0.vsix?dl=0)
**VS Code plugin with this PR applied**: [8.0.0 plugin](https://www.dropbox.com/s/a27k44e1x3knbr0/KOGITO-4530.vsix?dl=0)
> [8.0.0] KOGITO-4530: [DMN Designer] Boxed Expressions - Decision Tables - HiDPI is not working as expected

- drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapper.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchEntryPoint.java
See [KOGITO-4868](https://issues.redhat.com/browse/KOGITO-4868)
> KOGITO-4868: SceSim scroll fix

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/common/IdUtils.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/common/IdUtilsTest.java
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/DMNDesignerKogitoSeleniumIT.java
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/selenium/call-center.xml
**JIRA**: [KOGITO-4916](https://issues.redhat.com/browse/KOGITO-4916): [DMN Designer] Error during during the save/marshaller of specific diagrams
--
Cherry-picked from https://github.com/kiegroup/kie-wb-common/pull/3617
--
**VS Code plugin without this PR applied**: [8.0.0 plugin](https://www.dropbox.com/s/goihljb5n0f3q9v/current-8.0.0.vsix?dl=0)
**VS Code plugin with this PR applied**: [8.0.0 plugin](https://www.dropbox.com/s/82vrgfj6u23ofcy/KOGITO-4916.vsix?dl=0)
> [8.0.0] KOGITO-4916: [DMN Designer] Error during during the save/marshaller of specific diagrams

- kie-wb-common-stunner/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/traverse/content/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-lienzo-extensions/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/README.md
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/README.md
Hi @romartin , there are some readme fixes we talked about, no code/configurations changed.
Thank you!
> Readme sync with actual state after the fork

- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientParser.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/workitem/WorkItemDefinitionClientParserTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/resources/org/kie/workbench/common/stunner/bpmn/client/workitem/listParameters.wid
JIRA: [KOGITO-5004](https://issues.redhat.com/browse/KOGITO-5004)
VS Code: [plugin](https://drive.google.com/file/d/1yDVHke4wk16vItFl2U-ZTT42yfvOmD1w/view?usp=sharing)
Hi @romartin, @domhanak, PR is ready for review. Thank you!
> KOGITO-5004 - Unable to view service tasks in VSCode if wid file has mavenDependencies tag

- appformer-js-monaco/package.json
- appformer-js-monaco/yarn.lock
This PR fixes the icons on the suggestions box on Monaco Editor.
> Upgrade @kiegroup/monaco-editor with codeicon font fix

- .github/workflows/ci_full_downstream_build.yml
Since we changed the trigger from `pull_request` to `pull_request_target`, we need to merge the changes coming from PRs for this repository as well.
> FDB for PRs: Merge changes from PRs

- .github/workflows/bump_version.yml
- bump_version.sh
Script and workflow to make it easy to bump versions.
The workflow takes the `new_version` as input and creates a pull request with the changes.
> Bump version script and workflow

- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/LienzoMultipleSelectionControl.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/AbstractSelectionControl.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControl.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/select/MapSelectionControlTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-forms/kie-wb-common-stunner-forms-client/src/main/java/org/kie/workbench/common/stunner/forms/client/widgets/FormsCanvasSessionHandler.java
Hi @romartin can you review this PR?
> KOGITO-4935 : [DMN/BPMN editor] Sometimes clicking outside doesn't unselect nodes

- .github/workflows/ci_full_downstream_build.yml
See kiegroup/kogito-tooling#513
> Updating Node and Yarn on the FDB workflow

- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/GeneralCreateNodeAction.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/canvas/controls/BPMNCreateNodeAction.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/canvas/controls/BPMNCreateNodeActionTest.java
Hi @romartin can you review this PR? Artifact can be found here. https://drive.google.com/drive/folders/1tjkhXfTHDic8Ef4wiLLmx3pgzK70RIiQ?usp=sharing
> KOGITO-4671 : New elements should always be connected by its central magnetic point

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshaller.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnector.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/marshall/DMNMarshallerTest.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnectorTest.java
See: [KOGITO-5003](https://issues.redhat.com/browse/KOGITO-5003)
> KOGITO-5003: DMN editor removing edges for duplicate Decision Nodes on canvas

- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/util/ShapeViewUserDataEncoder.java
- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/util/ShapeViewUserDataEncoderTest.java
Hey @jstastny-cz @nmirasch 
This is the cherry-pick of the improvemetns on the ids for the generated SVG, but into the kogito editors stream. The cherry-pick has produced no conflicts and I've tested the generated SVG, but appreciate also verify from your side, as you did in the soruce commit:
https://github.com/kiegroup/kie-wb-common/pull/3634
Thanks!
> JBPM-9708: BPMN Editor - Improve SVG generated ids (#3634)

- appformer-js-monaco/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1353
The other chance is to change for the whole RHBA repositories https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1668
> BXMSPROD-1353 nodejs v16.2.0

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/actions/DMNCreateNodeAction.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/actions/DMNCreateNodeActionTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasLayoutUtils.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/GeneralCreateNodeAction.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasLayoutUtilsTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/CreateNodeToolboxActionTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/GeneralCreateNodeActionTest.java
See: https://issues.redhat.com/browse/KOGITO-4043
> KOGITO-4043: The nodes should be created on top of the selected node in DMN editor

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/keyboard/shortcut/AppendDecisionShortcut.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/keyboard/shortcut/AppendDecisionShortcutTest.java
See: https://issues.redhat.com/browse/KOGITO-5489
[Vsix](https://drive.google.com/file/d/1JDSpVsuczBPz9yxaf-nEot1CCYbGX6cS/view?usp=sharing)
> KOGITO-5489: [DMN Designer] When users create a node by using a shortcut, it's not created above

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/actions/DMNCreateNodeAction.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/builder/ObserverBuilderControl.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/inlineeditor/DMNCanvasInlineTextEditorControl.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/canvas/controls/inlineeditor/DMNCanvasInlineTextEditorControlTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImpl.java
- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionPresenterView.html
- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/inlineeditor/InlineTextEditorBoxViewImplTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/builder/impl/ObserverBuilderControl.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/InlineTextEditEvent.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/GeneralCreateNodeAction.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/components/toolbox/actions/GeneralCreateNodeActionTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/canvas/controls/BPMNCreateNodeAction.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/canvas/controls/BPMNInlineTextEditorControl.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/canvas/controls/BPMNInlineTextEditorControlTest.java
Hi @romartin please find this PR for this ticket. 
It also fixes KOGITO-5036 about issue with Imported nodes being editable
Artifact can be found here. https://drive.google.com/drive/folders/1zF8JxV0phIgRFJktqFwiUp3SjITc0oEy?usp=sharing
> KOGITO-4978 : Make new nodes Editable

- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/src/main/java/org/eclipse/emf/ecore/xmi/resource/xml/XMLLoad.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-emf/src/test/java/org/kie/workbench/common/stunner/bpmn/client/emf/Bpmn2MarshallingTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/VariableDeclaration.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/VariableDeclarationTest.java
Hi @romartin applied changes 1) Enable Comments on XML 2) Enable empty variable name on Multiple Instance can you please review this PR?
> Kogito-5470 : Cannot import process

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeList.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListTest.java
See https://issues.redhat.com/browse/KOGITO-1625
[VSCode Plugin](https://drive.google.com/file/d/1N2RIFKsysfYGiqmJxllhurDnSSpQ0qVe/view?usp=sharing)
> KOGITO-1625: [DMN Designer] Data Types changes do not mark asset as dirty

- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/DataObject.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/activities/ReusableSubprocessConverter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/artifacts/DataObjectConverter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/processes/RootProcessConverter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/DataObjectPropertyWriter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/EventPropertyWriter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/PropertyWriter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/activities/CallActivityConverter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/artifacts/DataObjectConverter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/RootProcessConverter.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/EventPropertyReader.java
Hi @romartin as discussed, removing calls to replaceIllegalChars, since gwt classes do that now. Can you review this PR?
> KOGITO-5506 : BPMN Editor - Marshallers encoding issues

- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/common/DMNDesignerBaseIT.java
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/DMNDesignerKogitoSeleniumIT.java
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/resources/org/kie/workbench/common/dmn/showcase/client/selenium/bend-points.xml
Dependent on https://github.com/kiegroup/kogito-editors-java/pull/78
> KOGITO-5119: Add DMN diagram bend points marshalling test

- kogito-editors-js/package.json
- kogito-editors-js/packages/boxed-expression-component/showcase/cypress/integration/context_expression_spec.ts
- kogito-editors-js/packages/boxed-expression-component/showcase/cypress/integration/relation_expression_spec.ts
- kogito-editors-js/packages/boxed-expression-component/showcase/package.json
- kogito-editors-js/packages/boxed-expression-component/showcase/src/index.tsx
- kogito-editors-js/packages/boxed-expression-component/src/components/Table/Table.tsx
- kogito-editors-js/yarn.lock
Dependent on a https://github.com/kiegroup/kogito-editors-java/pull/82
> KOGITO-5481: Add 50x50 Relation cypress test

- lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/wires/proxy/WiresDragProxy.java
- lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/wires/proxy/WiresDragProxyTest.java
Hi @romartin can you review this PR? Added both the fix and unit test, thanks
> KOGITO-5469 : Can't connect elements vertically far from each other in a BPMN Diagram

- lienzo-core/src/main/java/com/ait/lienzo/tools/client/event/HandlerManager.java
- lienzo-tests/src/test/java/com/ait/lienzo/tools/client/event/HandlerManagerTest.java
Hey @romartin, could you review this PR Please?
**VS Code**: [plugin](https://drive.google.com/file/d/1P0IXVVS1-8sJrMEMKm_WGAFZJ2OB7zCf/view?usp=sharing)
Thanks
> KOGITO-5594: [Stunner] bend point modification causes diagram inaccessible

- errai-common/src/main/java/org/jboss/errai/common/metadata/ErraiPropertyScanner.java
- errai-common/src/main/java/org/jboss/errai/common/metadata/RebindUtils.java
- errai-common/src/main/java/org/jboss/errai/common/rebind/ModuleAnnotationProcessor.java
- errai-reflections/reflections/src/main/java/org/jboss/errai/reflections/serializers/XmlSerializer.java
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/TranslationServiceGenerator.java
- kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/session/DMNEditorSessionTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-svg/kie-wb-common-stunner-svg-gen/src/main/java/org/kie/workbench/common/stunner/svg/gen/impl/SVGGeneratorImpl.java
- kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorWidget.css
- https://issues.redhat.com/browse/KOGITO-5642
> Kogito-5642: Fix blocker issues found by sonar

- kogito-editors-js/packages/import-java-classes-component/showcase/src/index.tsx
- kogito-editors-js/packages/import-java-classes-component/src/__tests__/ImportJavaClasses/ImportJavaClasses.test.tsx
- kogito-editors-js/packages/import-java-classes-component/src/__tests__/ImportJavaClasses/__snapshots__/ImportJavaClasses.test.tsx.snap
- kogito-editors-js/packages/import-java-classes-component/src/api/ImportJavaClasses.ts
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizard.tsx
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardClassListTable.tsx
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardFieldListTable.tsx
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardFirstStep.tsx
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardSecondStep.tsx
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/Model/JavaClass.ts
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/Model/JavaClassField.ts
- kogito-editors-js/packages/import-java-classes-component/src/components/ImportJavaClasses/Model/index.ts
- kogito-editors-js/packages/import-java-classes-component/src/i18n/locales/en.ts
https://issues.redhat.com/browse/KOGITO-5149
Demo avaliable here: https://yesamer.github.io/kogito-editors-java/
> KOGITO-5149: Create the second step of the Wizard - Create the collapsible/expandable list of future Data Types

- .ci/jenkins/Jenkinsfile
- .ci/jenkins/dsl/Jenkinsfile.seed
- .ci/jenkins/dsl/jobs.groovy
- .ci/jenkins/dsl/test.sh
- .github/workflows/sonar_analysis_kiegroup.yml
- appformer-bom/pom.xml
- drools-wb-bom/pom.xml
- drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-marshaller/src/test/java/org/drools/workbench/scenariosimulation/kogito/marshaller/ScesimGwtJsonixTest.java
- errai-bom/pom.xml
- kie-wb-common-bom/pom.xml
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml
- kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/pom.xml
- kogito-editors-js/pom.xml
- lienzo-webapp/pom.xml
- pom.xml
Ensemble together with:
- https://github.com/kiegroup/kogito-pipelines/pull/253
> KOGITO-5642: Activate sonar check

- .github/workflows/sonar_analysis_kiegroup.yml
- https://github.com/kiegroup/kogito-editors-java/actions/runs/1234074225
> Fix indentation in on:push sonar github action

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeView.less
- https://issues.redhat.com/browse/DROOLS-4719
> DROOLS-4719: Change decision navigator DRG icon

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.html
- kogito-editors-js/packages/boxed-expression-component/src/components/BoxedExpressionEditor/BoxedExpressionEditor.tsx
Quick fix for removing CSS conflict file and hiding button for switching to new editor
> [KOGITO-6188] Removing CSS conflict file and hiding button for switching to new editor

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListView.less
> RHDM-1611: Show vertical scrollbar on small screen for data types placeholder

- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/LienzoCanvas.java
- kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/ViewEventHandlerManager.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvas.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/AbstractClientSessionCommand.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommand.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvasTest.java
- kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/session/command/impl/DeleteSelectionSessionCommandTest.java
VSIX: https://drive.google.com/file/d/1SBl1r35MtzrYNsE2wgXkioLQqd_gW9ai/view?usp=sharing
Ticket: https://issues.redhat.com/browse/KOGITO-6132
> KOGITO-6132: [DMN Designer] Pressing backspace when editing a node deletes the node

- kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClauseUnaryTests.java
> RHPAM-3329: Increase Decision Table Output value length limit

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/DMNMarshallerService.java
- https://issues.redhat.com/browse/KOGITO-6144
Ensemble together with:
- https://github.com/kiegroup/kogito-tooling/pull/658
> KOGITO-6144: add xml declaration prolog

- kogito-editors-js/packages/boxed-expression-component/showcase/cypress/integration/context_expression_spec.ts
- kogito-editors-js/packages/boxed-expression-component/showcase/cypress/support/commands.d.ts
- kogito-editors-js/packages/boxed-expression-component/showcase/cypress/support/commands.ts
KOGITO-6262: Extend new boxed expression editor decision table coverage
- https://issues.redhat.com/browse/KOGITO-6262
Dependent on #159
> KOGITO-6262: Extend new boxed expression editor decision table coverage

- kogito-editors-js/.gitignore
- kogito-editors-js/packages/boxed-expression-component/showcase/cypress/integration/context_expression_spec.ts
> Enable tests for KOGITO-6262

- appformer-js-monaco/pom.xml
- kogito-editors-js/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1558
https://github.com/kiegroup/appformer/pull/1217
https://github.com/kiegroup/kie-wb-common/pull/3709
https://github.com/kiegroup/kogito-apps/pull/1141
https://github.com/kiegroup/kogito-editors-java/pull/184
https://github.com/kiegroup/optaweb-employee-rostering/pull/730
https://github.com/kiegroup/optaweb-vehicle-routing/pull/614
https://github.com/kiegroup/process-migration-service/pull/37
https://github.com/kiegroup/lock-treatment-tool/pull/2
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1840
https://github.com/kiegroup/kie-jenkins-scripts/pull/1175
> BXMSPROD-1558 install lock-treatment-tool exec

- kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/marshaller/included/DMNMarshallerImportsClientHelper.java
https://issues.redhat.com/browse/KOGITO-6403
No functionalities change in this PR, I just added Severe logs in case of failed Promises, in order to help investigate in case one of those Promises fails.
> KOGITO-6403: [DMN Designer] Adding logs in case of failed Promises in DMNMarshallerImportsClientHelper
